### ISSUE TITLE
How often should data be written?

### ISSUE THREAD

**Issue by jasonyates** [matthewwall/weewx-influx#10]
I'm a little confused how Weewx and influx is supposed to work.

I have a WH1080 connected to an RPi via USB, I get HTML based reports generated every 30 minutes, i can't seem to get it any faster than that which is a shame however, I setup this influx plugin, i see on restart it try and create a DB (it already exists) and then nothing else.

Perhaps i am misunderstanding how this works, but I was expecting data to be almost streamed to influx far faster than every 30 minutes?

**Comment by matthewwall** [comment]
a wh1080 will emit data every 48 seconds

you can poll faster than that, but it won't do any good since the sensors only update every 48 seconds

you need to set record_generation=software

and you should use wee_device to set the station's archive interval to 5 minutes instead of the factory default 30 minutes

see the weewx documentation:

http://weewx.com/docs/usersguide.htm#[FineOffsetUSB]

http://weewx.com/docs/hardware.htm#fousb_notes
