### ISSUE TITLE
Just "record" Measurement 

### ISSUE THREAD

**Issue by cbirkenbeul** [matthewwall/weewx-influx#2]
Hi,

yesterday i installed your plugin. Setup an influxdb server and tried to send the data to them. in my syslog in the weewx server are no errors about the sending of the data.

but if look into the database i only see the measurement record, nothing else. There are also no keys. Do i have to setup something special? I want all data in influxdb for long term graphics.

Thx.

**Comment by timraymond** [comment]
@cbirkenbeul By keys do you mean tag keys or field keys (or both)? This plugin won't write any tags along with your data if you haven't configured it to do so, so `show tag keys from record` will come up empty. You can see all the fields you can query for with `show field keys from record`, and this will be things like temperature, humidity, etc. This surprised me initially as well, since I usually explore tags first but writing all this data as fields and leaving tags for differentiating among multiple weather stations / locations is done correctly.
